Archive Entry
navikt/crm-henvendelse pull request #586
Opened 2024-01-17 12:09 UTC by EirikFladby

2024-01-22 06:09 UTC, mamikals requested changes
Har ikke sett over flowene, skal lage en scratch så æ faktisk kan lese de da

2024-01-22 06:09 UTC, mamikals commented on force-app/main/default/classes/ArchiveRerunBatch.cls
E detta bare en backup av det forrige eller? Detta skal vel ikke være her.

2024-01-22 06:09 UTC, mamikals commented on force-app/main/default/classes/ArchiveRerunner.cls
Samme med denna right? Denna e bare her for å fucke med mæ så æ trur PRen e større enn den e

2024-01-22 09:46 UTC, EirikFladby commented on force-app/main/default/classes/ArchiveBatch.cls
> +        Map<String, List<ArchiveService.ArchiveResponseWrapper>> responseByArchiveEntryId = new Map<String, List<ArchiveService.ArchiveResponseWrapper>>();
Hehe, den var for å mappe respons mot record før jeg håndterte respons for en hel liste

2024-01-22 09:49 UTC, EirikFladby commented on force-app/main/default/classes/ArchiveBatch.cls
> +            update archiveEntriesToUpdate;
Det var dette jeg snakka om på Slack. Enten kjøre én callout per record i batch som ikke er så pent, men da har vi muligheten til å få en unik respons per record. Ellers kjører vi én callout for en liste av records og alle records blir da håndtert med samme respons.

2024-01-22 09:59 UTC, EirikFladby commented on force-app/main/default/classes/ArchiveBatch.cls
> +    }
Vi kan sette opp til å kjøre i intervaller ja, men det som vil skje da er at tidspunktet vil forskyve seg. Hvis batchen settes opp til å kjøre hver 24 time, men batchen bruker 10 min på å fullføre, så kjøres neste batch 10 minutter etterpå, etc. Hvis vi vil prøve å holde antall batchjobber som kjører samtidig på et tidspunkt lavt så er det lurest å bruke cron exp for å kjøre på et bestemt tidspunkt. Så jeg fjerner dette også kjører vi bare System.schedule med cronexp i dev console.

2024-01-22 10:00 UTC, EirikFladby commented on force-app/main/default/classes/ArchiveRerunBatch.cls
Backup av forrige så vi kan rekjøre de arkiveringene som har feilet i det siste, ja 😄  Kan slettes når vi har implementert Archive Entry objektet.

2024-01-22 10:00 UTC, EirikFladby commented on force-app/main/default/classes/ArchiveRerunner.cls
Backup av forrige så vi kan rekjøre de arkiveringene som har feilet i det siste, ja 😄  Kan slettes når vi har implementert Archive Entry objektet.

2024-01-22 11:20 UTC, mamikals requested changes
Flowene så bra ut, utenom at jeg tenker det er unødvendig mange felter som blir satt i hver create for Archive Record subflowen. Det burde heller bare være en assign i starten som setter mesteparten av feltene og så en assign av status der hvor hver create record er nå, og til slutt en insert.
Men jeg er også generelt forvirret av archiveData feltet, det virker litt dumt å gjøre slike manuelle assignments og formateringer i flowen. Det er mye cleanere å lagre det som JSON. Kanskje en apex metode med input som en query, og returnerer JSON stringet som output?

2024-01-23 05:46 UTC, mamikals approved these changes

2024-01-24 20:43 UTC, merged