Archiveerrhandling
navikt/crm-henvendelse pull request #603
Opened 2024-02-15 11:35 UTC by EirikFladby

2024-02-15 12:31 UTC, mamikals requested changes

2024-02-15 12:31 UTC, mamikals commented on force-app/main/default/classes/ArchiveHandler.cls
> +
Dette virker unødvendig, jeg tror det er bedre å bare extende classen med CRM_ApplicationDomain 😄, da er det også nærmere det vi har gjort andre steder.

2024-02-15 12:31 UTC, mamikals commented on force-app/main/default/classes/ArchiveHandler.cls
>          return responseIds;
Kommer ikke dette til å faile i flow hvis det blir en exception? Hvordan fungerer det?

2024-02-15 13:40 UTC, EirikFladby commented on force-app/main/default/classes/ArchiveHandler.cls
>          return responseIds;
Hvis det blir en exception vil den catches og response vil være == null. Da vil flowen sette status failed på Archive Entry ettersom response id == null || ''

2024-02-15 14:52 UTC, mamikals commented on force-app/main/default/classes/ArchiveHandler.cls
>          return responseIds;
Nei jeg tror det kommer til å bli veildig fucked :), fordi inputtet er en liste og det du returnerer når response = null er ikke en liste med lik lengde, det er en tom liste.
Jeg tror du må lage en liste med X antall indexer som er null bare.

2024-02-16 07:45 UTC, mamikals approved these changes

2024-02-16 08:02 UTC, merged